MESSAGING_DB_HOST: '127.0.0.1'
MESSAGING_DB_USERNAME: sss
MESSAGING_DB_PASSWORD: '1234'
MESSAGING_DB_DATABASE_DEV: messaging_dev
MESSAGING_DB_DATABASE_TEST: messaging_test
MESSAGING_DB_DATABASE_PROD: messaging_prod
RAILS_MAX_THREADS: 5
