default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('MESSAGING_DB_HOST') { '127.0.0.1' } %>
  username: <%= ENV.fetch('MESSAGING_DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('MESSAGING_DB_PASSWORD') { 'dev' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: <%= ENV.fetch('MESSAGING_DB_DATABASE_DEV') { 'messaging_dev' } %>
test:
  <<: *default
  database: <%= ENV.fetch('MESSAGING_DB_DATABASE_TEST') { 'messaging_test' } %>
production:
  <<: *default
  database: <%= ENV.fetch('MESSAGING_DB_DATABASE_PROD') { 'messaging_prod' } %>
